app_main/urls.py
from django.urls import path
from app_main import views

app_name = 'main'

urlpatterns = [
    path('', views.HomeView.as_view(), name="home"), 
    path('dashboard/', views.main_view, name="dashboard"),
]

app_users/urls.py
from django.urls import path
from app_users import views

app_name = 'users'

urlpatterns = [
    path('', views.main_view, name="users"),
    path('register/', views.RegisterView.as_view(), name="register_view"),
    path('register/create', views.RegisterCreate.as_view(), name="register_create"),
    path('login/', views.LoginView.as_view(), name="login_view"),
    path('login/create', views.LoginCreate.as_view(), name="login_create"),
    path('logout/', views.Logout.as_view(), name="logout"),
    path('profile/<slug:slug>/', views.main_view, name="profile"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_main.urls')), # Home
    path('users/', include('app_users.urls')), # User managemant
    path('legends/', include('app_legends.urls')), # Legends system
    # path('d&d/'), # D&D system
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/templates/global/partials/crop-form.html
<div class="crop-form-container">
    <form action="" id="image-form">
        {% csrf_token %}
        {{ form.as_p }}
    </form>
    <div id="image-box"></div>
    <div class="buttons">
        <button class="not-visible" id="confirm-btn">Confirmar</button>
        <a href="{{ return }}">Voltar</a>
    </div>
</div>

base/templates/global/partials/crop.html
{% load static %}

<script src="{% static "jquery\dist\jquery.js" %}"></script><!-- jQuery is required -->
<link  href="{% static "cropper\dist\cropper.css" %}" rel="stylesheet">
<script src="{% static "cropper\dist\cropper.js" %}"></script>

<script src="{% static "global/js/crop.js" %}" defer></script>

base/templates/global/partials/footer.html
<footer class="footer-container">
    
</footer>

base/templates/global/partials/form.html
<div class="form-container">
    <div class="form-title">
        <h2>{{ form_title }}</h2>
    </div>
    {% include "global/partials/messages.html" %}
    <div class="form-content">
        <form action="{{ form_action }}" method="POST" enctype="multipart/form-data" id="form">
            {% csrf_token %}
            <div class="form-grid">
                {% for field in form %}
                    <div class="form-field {{ field.field.widget.attrs.class }}">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}

                        {% if field.help_text %}
                            <p class="form-help-text">{{ field.help_text }}</p>
                        {% endif %}

                        {{ field.errors }}
                    </div>
                {% endfor %}
            </div>

            <div class="form-submit">
                <button type="submit">Enviar</button>
            </div>
        </form>
    </div>
</div>

base/templates/global/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/brands.min.css" integrity="sha512-8RxmFOVaKQe/xtg6lbscU9DU0IRhURWEuiI0tXevv+lXbAHfkpamD4VKFQRto9WgfOJDwOZ74c/s9Yesv3VvIQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/fontawesome.min.css" integrity="sha512-d0olNN35C6VLiulAobxYHZiXJmq+vl+BGIgAxQtD5+kqudro/xNMvv2yIHAciGHpExsIbKX3iLg+0B6d0k4+ZA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/regular.min.css" integrity="sha512-TzeemgHmrSO404wTLeBd76DmPp5TjWY/f2SyZC6/3LsutDYMVYfOx2uh894kr0j9UM6x39LFHKTeLn99iz378A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/solid.min.css" integrity="sha512-pZlKGs7nEqF4zoG0egeK167l6yovsuL8ap30d07kA5AJUq+WysFlQ02DLXAmN3n0+H3JVz5ni8SJZnrOaYXWBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="stylesheet" href="{% static "global/css/global.css" %}">
<link rel="stylesheet" href="{% static "global/css/profile-dropdown.css" %}">
<link rel="stylesheet" href="{% static "global/css/systems-dropdown.css" %}">

base/templates/global/partials/header.html
{% load static %}

<header class="header-container">
    <div class="header-logo">
        <a href="{% url "main:home" %}">
            <img src="{% static "global/img/logo_temp.png" %}" alt="">
        </a>
    </div>
    <div class="header-dropdowns">
        {% include "global/partials/systems-dropdown.html" %}
        {% include "global/partials/profile-dropdown.html" %}
    </div>
</header>

base/templates/global/partials/messages.html
{% if messages %}
    <div class="message-container">
        {% for message in messages %}
            <div class="message {{ message.tags }}">
                {{ message }}
            </div>    
        {% endfor %}
    </div>
{% endif %}

base/templates/global/partials/profile-dropdown.html
<div class="profile-dropdown-container header-button">
    <button class="profile-dropdown-dropbtn"> 
        <i class="fa-solid fa-user"></i>
    </button>
    <div class="profile-dropdown-content">
        {% if request.user.is_authenticated %}

            <p>Olá, {{ request.user.username }}</p>

            <div class="profile-dropdown-separator"></div>

            <a href="/">Perfil</a>
            <a href="{% url "main:dashboard" %}">Painel</a>

            <div class="profile-dropdown-separator"></div>

            <form action="{% url "users:logout" %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="username" value="{{ request.user.username }}">
                <button type="submit">Sair</button>
            </form>
            
        {% else %}

            <a href="{% url "users:login_view" %}">Logar</a>
            <a href="{% url "users:register_view" %}">Criar conta</a>

        {% endif %}
    </div>
</div>

base/templates/global/partials/search.html
<div class="search-container">
    <div class="search-bar">
        <button class="search-filter"><i class="fa-solid fa-sliders"></i></button>
        <form action="" class="search-form">
            <input type="search" class="search-input" name="q" value="{{ search_term }}" required>
            <button type="submit" class="search-button"><i class="fa-solid fa-magnifying-glass"></i></button>
        </form>
    </div>
</div>

base/templates/global/partials/systems-dropdown.html
<div class="system-dropdown-container header-button">
    <button class="system-dropdown-dropbtn"> 
        Sistemas <i class="fa-solid fa-angle-down"></i>
    </button>
    <div class="system-dropdown-content">
        {% for system in systems %}
            <a href="/">{{ system.name }}</a>
        {% endfor %}
    </div>
</div>