app_legends/urls.py
from django.urls import path
from app_legends import views

app_name = 'legends'

urlpatterns = [
    path('', views.main_view, name="legends"),
    path('character/list/', views.CharactersList.as_view(), name="character_list"),
    path('character/sheet/<int:id>/', views.CharacterSheet.as_view(), name="character_sheet"),
    path('character/edit/info/<int:id>/', views.CharacterEdit.as_view(), name="character_edit"),
    path('character/edit/image/<int:id>/', views.character_edit_image, name="character_edit_image"),
    path('character/edit/attribute/<int:id>/', views.CharacterEditAttribute.as_view(), name="character_edit_attribute"),
    path('character/edit/expertise/<int:id>/', views.CharacterEditExpertise.as_view(), name="character_edit_expertise"),
    path('character/edit/stats/<int:id>/', views.CharacterEditStatsBars.as_view(), name="character_edit_stats"),
    path('character/edit/level/<int:id>/', views.CharacterEditLevel.as_view(), name="character_edit_level"),
    path('character/edit/skills/<int:id>/', views.CharacterEditSkills.as_view(), name="character_edit_skills"),

    path('character/weapon/create/<int:id>/', views.CharacterWeaponCreate.as_view(), name="character_weapon_create"),
    path('character/weapon/delete/<int:id>/', views.CharacterWeaponDelete.as_view(), name="character_weapon_delete"),
    path('character/weapon/update/name/<int:id>/', views.CharacterWeaponUpdateName.as_view(), name="character_weapon_update_name"),
    path('character/weapon/update/weapontype/<int:id>/', views.CharacterWeaponUpdateWeaponType.as_view(), name="character_weapon_update_weapon_type"),
    path('character/weapon/update/modifier/<int:id>/', views.CharacterWeaponUpdateModifier.as_view(), name="character_weapon_update_modifier"),
    path('character/weapon/update/damagetype/<int:id>/', views.CharacterWeaponUpdateDamageType.as_view(), name="character_weapon_update_damage_type"),

    path('race/list/', views.RaceList.as_view(), name="race_list"),
    path('race/<int:id>/', views.RaceSheet.as_view(), name="race"),

    path('specialization/<int:id>/', views.main_view, name="specialization"),
    path('skill/<int:id>/', views.SkillSheet.as_view(), name="skill"),

    path('spell/list/', views.SpellList.as_view(), name="spell_list"),
    path('spell/<int:id>/', views.SpellSheet.as_view(), name="spell"),

    path('item/<int:id>/', views.main_view, name="item"),
    path('search/', views.main_view, name="search"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_main.urls')), # Home
    path('users/', include('app_users.urls')), # User managemant
    path('legends/', include('app_legends.urls')), # Legends system
    # path('d&d/'), # D&D system
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_legends/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def main_view(request):
    return HttpResponse('App legends')

app_legends/views/character_edit.py
from django.views import View
from django.shortcuts import render, redirect
from django.urls import reverse
from app_legends.models import Character, CharacterStats, Race, Specialization, Skill
from app_legends.forms import CharacterEditForm
from app_main.models import RPGSystem
from django.http import Http404
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

@method_decorator(
    login_required(login_url='users:login_view', redirect_field_name='next'),
    name='dispatch'
)
class CharacterEdit(View):

    def get_character(self, request, id):
        character = Character.objects.filter(
            id=id,
            editor=request.user,
        ).first()

        if not character:
            raise Http404()

        return character
    
    def get_old_skills(self, character):
        old_skills = [character.specialization.startingSkill]
        old_skills += character.race.skills.all()

        return old_skills
    
    def get_new_skills(self, request):
        race = Race.objects.filter(
            id=request.POST.get('race')
        ).first()
        specialization = Specialization.objects.filter(
            id=request.POST.get('specialization')
        ).first()
        new_skills = [specialization.startingSkill]
        new_skills += race.skills.all()
        
        return new_skills

    def get(self, request, id):
        character = self.get_character(request, id)
        systems = RPGSystem.objects.all().order_by('name')

        form = CharacterEditForm(
            request.POST or None,
            request.FILES or None,
            instance=character
        )

        context = {
            'systems': systems,
            'form': form,
            'form_title': f'Editor de ficha - {character.name}',
            'character': character,
        }

        return render(request, 'legends/pages/character-edit.html', context)
    
    def post(self, request, id):
        character = self.get_character(request, id)
        old_skills = self.get_old_skills(character)
        character_stats = CharacterStats.objects.filter(character=character).first()

        form = CharacterEditForm(
            request.POST or None,
            request.FILES or None,
            instance=character
        )

        if form.is_valid():
            character = form.save(commit=False)
            if not character.creator:
                character.creator = request.user
            if not character.editor:
                character.editor = request.user

            new_skills = self.get_new_skills(request)
            for old_skill in old_skills:
                character.skills.remove(old_skill)
            for new_skill in new_skills:
                character.skills.add(new_skill)
            character.save()
            character_stats.save()
            
            messages.success(request, 'Personagem editado com sucesso!')
            
        return redirect(reverse('legends:character_sheet', kwargs={'id': id}))
    

app_legends/views/character_edit_attribute.py
from django.views import View
from django.shortcuts import render, redirect
from django.urls import reverse
from app_legends.models import Character, CharacterExpertise, CharacterAttribute
from app_legends.forms import CharacterEditForm
from app_main.models import RPGSystem
from django.http import Http404, JsonResponse
from django.contrib import messages

class CharacterEditAttribute(View):
    
    def post(self, request, id):
        character = Character.objects.filter(id=id).first()
        attribute_id = request.POST.get('attribute_id')
        attribute = CharacterAttribute.objects.filter(id=attribute_id).first()
        if attribute:
            if request.POST.get('type') == 'raise':
                if attribute.level < 70 and character.remainingPoints > 0:
                    attribute.level += 1
                    attribute.save()
                    character.save()
            if request.POST.get('type') == 'decrease':
                if attribute.level > 0 and attribute.remaining > 0:
                    attribute.level -= 1
                    attribute.save()
                    character.save()
            
        return redirect(reverse('legends:character_sheet', kwargs={'id': id}))
    

app_legends/views/character_edit_expertise.py
from django.views import View
from django.shortcuts import redirect
from django.urls import reverse
from app_legends.models import Character, CharacterExpertise, CharacterAttribute, CharacterStats, CharacterWeapon, Weapon

class CharacterEditExpertise(View):
    def post(self, request, id):
        character = Character.objects.filter(id=id).first()
        characterStats = CharacterStats.objects.filter(character=character).first()
        characterWeapons = CharacterWeapon.objects.filter(character=character).order_by('-id')
        attribute_id = request.POST.get('attribute_id')
        attribute = CharacterAttribute.objects.filter(id=attribute_id).first()
        expertise_id = request.POST.get('expertise_id')
        expertise = CharacterExpertise.objects.filter(id=expertise_id).first()
        if expertise and attribute:
            if request.POST.get('type') == 'raise':
                if expertise.level < 10 and attribute.remaining > 0:
                    expertise.level += 1
            if request.POST.get('type') == 'decrease':
                if expertise.level > -1:
                    expertise.level -= 1
            expertise.save()
            attribute.save()
            character.save()
            characterStats.save()
            for weapon in characterWeapons:
                weapon.save()
            
        return redirect(reverse('legends:character_sheet', kwargs={'id': id}))
    

app_legends/views/character_edit_image.py
from django.views import View
from django.shortcuts import render, redirect
from django.db.models import Q
from app_legends.models import Character
from app_legends.forms import CharacterEditImageForm
from app_main.models import RPGSystem
from django.http import Http404
from django.urls import reverse
from django.contrib import messages

class CharacterEditImage(View):
    ...
    # def get_character(self, request, id):
    #     character = Character.objects.filter(
    #         Q(public=True) |
    #         Q(editor=request.user),
    #         id=id,
    #     ).first()
    #     if not character:
    #         raise Http404()
    #     return character

    # def get(self, request, id):
    #     systems = RPGSystem.objects.all().order_by('name')
    #     character = self.get_character(request, id)
    #     form = CharacterEditImageForm(request.POST or None, request.FILES or None)
    #     context = {
    #         'systems': systems,
    #         'header_title': 'Legends',
    #         'character': character,
    #         'form': form,
    #     }

    #     return render(request, 'legends/pages/character_edit_image.html', context)
    
    # def post(self, request, id):
    #     character = self.get_character(request, id)
    #     form = CharacterEditImageForm(request.POST or None, request.FILES or None)

    #     if form.is_valid():
    #         print('deu certo')
        
    #     url = reverse('legends:character_list')
    #     return redirect(url)

def character_edit_image(request, id):
    character = Character.objects.filter(
            Q(public=True) |
            Q(editor=request.user),
            id=id,
        ).first()
    form = CharacterEditImageForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        new_instance = form.save(commit=False)
        character.ilustration = new_instance.ilustration
        character.save()

    context = {
        'form': form,
        'return': reverse('legends:character_sheet', args={id,}),
    }
    return render(request, 'legends/pages/character-edit-image.html', context)

app_legends/views/character_edit_level.py
from django.views import View
from django.shortcuts import redirect
from django.urls import reverse
from app_legends.models import Character, CharacterExpertise, CharacterAttribute, CharacterStats

class CharacterEditLevel(View):
    
    def post(self, request, id):
        character = Character.objects.filter(id=id).first()
        character_stats = CharacterStats.objects.filter(character=character).first()
        character_expertises = CharacterExpertise.objects.filter(character=character)
        new_level = int(request.POST.get('level'))
        if new_level > 20:
            new_level = 20
        elif new_level < 1:
            new_level = 1
        character.level = new_level 
        character.save()
        character_stats.save()
        for expertise in character_expertises:
            expertise.save()
            
        return redirect(reverse('legends:character_sheet', kwargs={'id': id}))
    

app_legends/views/character_edit_skills.py
from django.views import View
from django.shortcuts import redirect
from django.urls import reverse
from app_legends.models import Character, CharacterStats, CharacterExpertise

class CharacterEditSkills(View):
    
    def post(self, request, id):
        character = Character.objects.filter(id=id).first()
        character_stats = CharacterStats.objects.filter(character=character).first()
        character_expertise = CharacterExpertise.objects.filter(character=character).first()
        character.skills.set(request.POST.getlist('skills'))
        character.save()
        character_stats.save()
        character_expertise.save()
            
        return redirect(reverse('legends:character_sheet', kwargs={'id': id}))
    

app_legends/views/character_edit_stats_bars.py
from django.views import View
from django.shortcuts import redirect
from django.urls import reverse
from app_legends.models import Character, CharacterStats

class CharacterEditStatsBars(View):
    
    def post(self, request, id):
        character = Character.objects.filter(id=id).first()
        character_stats = CharacterStats.objects.filter(character=character).first()
        if request.POST.get('type') == 'energy':
            character_stats.currentEP = int(request.POST.get('current_ep'))
            character_stats.save()
        if request.POST.get('type') == 'health':
            character_stats.currentHP = int(request.POST.get('current_hp'))
            character_stats.save()
            
        return redirect(reverse('legends:character_sheet', kwargs={'id': id}))
    

app_legends/views/character_sheet.py
from django.views import View
from django.shortcuts import render, redirect
from django.db.models import Q
from app_legends.forms import CharacterEditSkillsForm
from app_legends.models import Character, CharacterAttribute, CharacterExpertise, CharacterStats, CharacterWeapon, Weapon, DamageType
from app_main.models import RPGSystem
from django.http import Http404

class CharacterSheet(View):

    def get(self, request, id):
        systems = RPGSystem.objects.all().order_by('name')
        character = Character.objects.filter(
            Q(public=True) |
            Q(editor=request.user),
            id=id,
        ).first()
        if not character:
            raise Http404()
        character_attributes = CharacterAttribute.objects.filter(
            character=character
        ).order_by('id')
        character_expertises = CharacterExpertise.objects.filter(
            character=character
        ).order_by('id')
        character_stats = CharacterStats.objects.filter(
            character=character
        ).first()
        character_weapons = CharacterWeapon.objects.filter(
            character=character
        ).order_by('id')
        base_weapons = Weapon.objects.filter(
            rarity='Comum'
        ).order_by('combat', '-type')
        damage_types = DamageType.objects.all().order_by('name')
        skills_form = CharacterEditSkillsForm(
            request.POST or None,
            instance=character
        )
        
        context = {
            'systems': systems,
            'header_title': 'Legends',
            'base_weapons': base_weapons,
            'character': character,
            'char_attrs': character_attributes,
            'char_exper': character_expertises,
            'char_stats': character_stats,
            'char_weapons': character_weapons,
            'damage_types': damage_types,
            'skills_form': skills_form,
        }

        return render(request, 'legends/pages/character-sheet.html', context)
    
    def post(self, request, id):
        return redirect('legends:character_sheet', kwargs={'id': id})

app_legends/views/character_weapon_create.py
from django.views import View
from django.shortcuts import redirect
from django.urls import reverse
from app_legends.models import Character, CharacterWeapon, Weapon

class CharacterWeaponCreate(View):
    def post(self, request, id):
        character = Character.objects.filter(
            id=id
        ).first()
        base_weapon = Weapon.objects.filter(
            name='Porrete'
        ).first()
        new_character_weapon = CharacterWeapon.objects.create(
            character=character,
            weapon=base_weapon,
            name='Nova arma!',
            damageType=base_weapon.damageType,
            weight=base_weapon.weight,
        )

        character.save()
        new_character_weapon.save()
            
        return redirect(reverse('legends:character_sheet', kwargs={'id': id}))
    

app_legends/views/character_weapon_delete.py
from django.views import View
from django.shortcuts import redirect
from django.urls import reverse
from app_legends.models import CharacterWeapon

class CharacterWeaponDelete(View):
    def post(self, request, id):
        character_weapon = CharacterWeapon.objects.filter(
            id=id
        ).first()
        character_id = character_weapon.character.id
        character_weapon.delete()
            
        return redirect(reverse('legends:character_sheet', kwargs={'id': character_id}))
    

app_legends/templates/legends/pages/character-edit-image.html
{% extends "global/pages/base.html" %}

{% load static %}

{% block style %}
    {% comment %} <link rel="stylesheet" href="{% static "legends/css/character-sheet.css" %}"> {% endcomment %}
    {% include "global/partials/crop.html" %}
{% endblock style %}

{% block title %}Editar imagem{% endblock title %}

{% block content %}
    {% include "global/partials/crop-form.html" %}
{% endblock content %}

app_legends/templates/legends/pages/character-list.html
{% extends "global/pages/base.html" %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static "global/css/search.css" %}">
    <link rel="stylesheet" href="{% static "legends/css/character-list.css" %}">
{% endblock style %}

{% block title %}Personagens | Legends{% endblock title %}

{% block content %}
    <div class="character-list-container">
        <h2>Personagens Jogáveis</h2>
        {% include "global/partials/search.html" %}
        <div class="character-list-content">
            {% for character in characters %}
                {% include "legends/partials/character_card.html" %}
                {% include "legends/partials/character_card.html" %}
                {% include "legends/partials/character_card.html" %}
                {% include "legends/partials/character_card.html" %}
            {% empty %}
                <p>Nenhum personagem encontrado.</p>
            {% endfor %}
        </div>
    </div>
{% endblock content %}


app_legends/templates/legends/pages/character-sheet.html
{% extends "global/pages/base.html" %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static "legends/css/character-sheet.css" %}">
    <script src="{% static "legends/js/stats-bar.js" %}"></script>
    <script src="{% static "legends/js/dice-roller.js" %}"></script>
{% endblock style %}

{% block title %}{{ character.name }} | Legends{% endblock title %}

{% block content %}
    <h2 class="character-sheet-name">{{ character.name }}</h2>
    {% if character.title %}
        <h5 class="character-sheet-title">{{ character.title }}</h5>
    {% endif %}
    <div class="character-sheet-container">
        {% include "legends/partials/character-sheet-header.html" %}
        {% include "legends/partials/character-sheet-stats.html" %}
        {% include "legends/partials/character-sheet-habilities.html" %}
        <div class="character-sheet-equipment">
            <h2>EQUIPAMENTO</h2>
            <div class="equipment-container">
                <div class="weapons-container">
                    <h3>Armas</h3>
                    <div class="weapons-grid">
                        {% include "legends/partials/character-sheet-weapon-card-header.html" %}
                        {% for weapon in char_weapons %}
                            {% include "legends/partials/character-sheet-weapon-card.html" %}
                        {% endfor %}
                        <div class="weapon-add">
                            <form action="{% url "legends:character_weapon_create" character.id %}" method="POST">
                                {% csrf_token %}
                                <button class="weapon-create-button"><i class="fa-solid fa-plus"></i> Adicionar Arma</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="equiped-container">
                    <div class="armor-container">
                        <h3>Armadura</h3>
                    </div>
                    <div class="talismans-container">
                        <h3>Talismãs</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}


app_legends/templates/legends/pages/character_edit.html
{% extends "global/pages/base.html" %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static "legends/css/forms.css" %}">
    <link rel="stylesheet" href="{% static "legends/css/character-edit.css" %}">
{% endblock style %}

{% block title %}{{ character.name }} | Legends{% endblock title %}

{% block content %}
    {% include "global/partials/form.html" %}
{% endblock content %}


app_legends/templates/legends/pages/character_edit_image.html
{% extends "global/pages/base.html" %}

{% load static %}

{% block style %}
    {% comment %} <link rel="stylesheet" href="{% static "legends/css/character-sheet.css" %}"> {% endcomment %}
    {% include "global/partials/crop.html" %}
{% endblock style %}

{% block title %}Editar imagem{% endblock title %}

{% block content %}
    {% include "global/partials/crop-form.html" %}
{% endblock content %}

app_legends/templates/legends/pages/character_sheet.html
{% extends "global/pages/base.html" %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static "legends/css/character-sheet.css" %}">
    <script src="{% static "legends/js/stats-bar.js" %}"></script>
{% endblock style %}

{% block title %}{{ character.name }} | Legends{% endblock title %}

{% block content %}
    <h2 class="character-sheet-name">{{ character.name }}{% if character.title %}, {{ character.title }}{% endif %}</h2>
    <div class="character-sheet-container">
        <div class="character-sheet-header">
            <div class="character-sheet-ilustration">
                {% include "legends/partials/character-sheet-ilustration.html" %}
            </div>
            <div class="character-sheet-points">
                <div class="character-sheet-attributes">
                    {% for attr in char_attrs %}
                        {% include "legends/partials/character-sheet-attribute-card.html" %}
                    {% endfor %}
                </div>
                <div class="character-sheet-expertises">
                    {% include "legends/partials/character-sheet-expertises.html" %}
                </div>
            </div>
        </div>
        {% include "legends/partials/character-sheet-stats.html" %}
        <div class="habilities">
            <div class="current-habilities">
                <h3>Habilidades</h3>
                <div class="habilities-grid">
                    {% for skill in character.skills.all %}
                        <ul><li><a href="{% url "legends:skill" skill.id %}">{{ skill.name }}</a></li></ul>
                    {% endfor %}
                </div>
            </div>
            <div class="edit-habilities">
                <h3>Editar</h3>
                <form action="{% url "legends:character_edit_skills" character.id %}" method="post">
                    {% csrf_token %}
                    <div class="habilities-container">
                        {% for field in skills_form %}
                            {{ field }}
                        {% endfor %}
                    </div>
                    <button type="submit">Atualizar</button>
                </form>   
            </div>
        </div>
    </div>
{% endblock content %}


app_legends/templates/legends/pages/race-sheet.html
{% extends "global/pages/base.html" %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static "legends/css/race-sheet.css" %}">
{% endblock style %}

{% block title %}{{ race.name }} | Legends{% endblock title %}

{% block content %}
    <h1 class="race-sheet-name">{{ race.name }}</h1>
    <h2 class="race-sheet-title">{{ race.title }}</h2>
    <div class="race-sheet-container">
        <div class="race-sheet-header">
            <div class="race-sheet-ilustration">
                <img src="{{ race.ilustration.url }}" alt="">
            </div>
            <div class="race-sheet-description">
                <p>{{ race.description }}</p>
            </div>
        </div>
        {% include "legends/partials/race-sheet-traits.html" %}
        <div class="race-sheet-skills">
            <h2 class="race-sheet-title border-bt">Habilidades da raça</h2>
            <div class="race-sheet-skills-list">
                {% for skill in skills %}
                    <div class="race-sheet-skills-grid-item">
                        <h3>{{ skill.name }}</h3>
                        <div class="race-sheet-skills-grid-content">
                            <p>{{ skill.description }}</p>
                        </div>
                    </div>
                {% empty %}
                    <div class="message span-2">
                        <p>Essa raça não possui nenhuma habilidade.</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}


app_legends/templates/legends/pages/race_sheet.html
{% extends "global/pages/base.html" %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static "legends/css/race-sheet.css" %}">
{% endblock style %}

{% block title %}{{ race.name }} | Legends{% endblock title %}

{% block content %}
    <h1 class="race-sheet-name">{{ race.name }}</h1>
    <h2 class="race-sheet-title">{{ race.title }}</h2>
    <div class="race-sheet-container">
        <div class="race-sheet-header">
            <div class="race-sheet-ilustration">
                <img src="{{ race.ilustration.url }}" alt="">
            </div>
            <div class="race-sheet-description">
                <p>{{ race.description }}</p>
            </div>
        </div>
        {% include "legends/partials/race-sheet-traits.html" %}
        <div class="race-sheet-skills">
            <h2 class="race-sheet-title border-bt">Habilidades da raça</h2>
            <div class="race-sheet-skills-list">
                {% for skill in skills %}
                    <div class="race-sheet-skills-grid-item">
                        <h3>{{ skill.name }}</h3>
                        <div class="race-sheet-skills-grid-content">
                            <p>{{ skill.description }}</p>
                        </div>
                    </div>
                {% empty %}
                    <div class="message span-2">
                        <p>Essa raça não possui nenhuma habilidade.</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}


app_legends/templates/legends/pages/skill-sheet.html
{% extends "global/pages/base.html" %}

{% load static %}

{% block style %}
    {% comment %} <link rel="stylesheet" href="{% static "legends/css/race-sheet.css" %}"> {% endcomment %}
{% endblock style %}

{% block title %}{{ skill.name }} | Legends{% endblock title %}

{% block content %}
    <h1 class="skill-sheet-name">{{ skill.name }}</h1>
    <div class="skill-sheet-container">
        <div class="skill-sheet-description">
            <p>{{ skill.description }}</p>
        </div>
    </div>
{% endblock content %}


app_legends/templates/legends/pages/skill_sheet.html
{% extends "global/pages/base.html" %}

{% load static %}

{% block style %}
    {% comment %} <link rel="stylesheet" href="{% static "legends/css/race-sheet.css" %}"> {% endcomment %}
{% endblock style %}

{% block title %}{{ skill.name }} | Legends{% endblock title %}

{% block content %}
    <h1 class="skill-sheet-name">{{ skill.name }}</h1>
    <div class="skill-sheet-container">
        <div class="skill-sheet-description">
            <p>{{ skill.description }}</p>
        </div>
    </div>
{% endblock content %}


app_legends/templates/legends/pages/specialization-sheet.html
{% extends "global/pages/base.html" %}

{% load static %}

{% block style %}
    {% comment %} <link rel="stylesheet" href="{% static "legends/css/specialization-sheet.css" %}"> {% endcomment %}
{% endblock style %}

{% block title %}{{ specialization.name }} | Legends{% endblock title %}

{% block content %}
    <h1 class="specialization-sheet-name">{{ specialization.name }}</h1>
    <h2 class="specialization-sheet-title">{{ specialization.title }}</h2>
    <div class="specialization-sheet-container">
        <div class="specialization-sheet-header">
            <div class="specialization-sheet-ilustration">
                <img src="{{ specialization.ilustration.url }}" alt="">
            </div>
            <div class="specialization-sheet-description">
                <p>{{ specialization.description }}</p>
            </div>
        </div>
        {% include "legends/partials/specialization-sheet-traits.html" %}
        <div class="specialization-sheet-skills">
            <h2 class="specialization-sheet-title border-bt">Habilidades da raça</h2>
            <div class="specialization-sheet-skills-list">
                {% for skill in skills %}
                    <div class="specialization-sheet-skills-grid-item">
                        <h3>{{ skill.name }}</h3>
                        <div class="specialization-sheet-skills-grid-content">
                            <p>{{ skill.description }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}


app_legends/templates/legends/pages/spell-sheet.html
{% extends "global/pages/base.html" %}

{% load static %}

{% block style %}
    {% comment %} <link rel="stylesheet" href="{% static "legends/css/race-sheet.css" %}"> {% endcomment %}
{% endblock style %}

{% block title %}{{ spell.name }} | Legends{% endblock title %}

{% block content %}
    <h1 class="spell-sheet-name">{% for element in spell.elements.all %}{{ element.icon|safe }}{% endfor %}{{ spell.name }}</h1>
    <div class="spell-sheet-container">
        <div class="spell-sheet-description">
            <p>{{ spell.description }}</p>
        </div>
    </div>
{% endblock content %}
