app_legends/urls.py
from django.urls import path
from app_legends import views

app_name = 'legends'

urlpatterns = [
    path('', views.main_view, name="legends"),
    path('character/list/', views.CharactersList.as_view(), name="character_list"),
    path('character/sheet/<int:id>/', views.CharacterSheet.as_view(), name="character_sheet"),
    path('character/edit/info/<int:id>/', views.CharacterEdit.as_view(), name="character_edit"),
    path('character/edit/image/<int:id>/', views.character_edit_image, name="character_edit_image"),
    path('character/edit/attribute/<int:id>/', views.CharacterEditAttribute.as_view(), name="character_edit_attribute"),
    path('character/edit/expertise/<int:id>/', views.CharacterEditExpertise.as_view(), name="character_edit_expertise"),
    path('character/edit/stats/<int:id>/', views.CharacterEditStatsBars.as_view(), name="character_edit_stats"),
    path('character/edit/level/<int:id>/', views.CharacterEditLevel.as_view(), name="character_edit_level"),
    path('character/edit/skills/<int:id>/', views.CharacterEditSkills.as_view(), name="character_edit_skills"),

    path('character/weapon/create/<int:id>/', views.CharacterWeaponCreate.as_view(), name="character_weapon_create"),
    path('character/weapon/delete/<int:id>/', views.CharacterWeaponDelete.as_view(), name="character_weapon_delete"),
    path('character/weapon/update/name/<int:id>/', views.CharacterWeaponUpdateName.as_view(), name="character_weapon_update_name"),
    path('character/weapon/update/weapontype/<int:id>/', views.CharacterWeaponUpdateWeaponType.as_view(), name="character_weapon_update_weapon_type"),
    path('character/weapon/update/modifier/<int:id>/', views.CharacterWeaponUpdateModifier.as_view(), name="character_weapon_update_modifier"),
    path('character/weapon/update/damagetype/<int:id>/', views.CharacterWeaponUpdateDamageType.as_view(), name="character_weapon_update_damage_type"),

    path('race/list/', views.RaceList.as_view(), name="race_list"),
    path('race/<int:id>/', views.RaceSheet.as_view(), name="race"),

    path('specialization/<int:id>/', views.main_view, name="specialization"),
    path('skill/<int:id>/', views.SkillSheet.as_view(), name="skill"),

    path('spell/list/', views.SpellList.as_view(), name="spell_list"),
    path('spell/<int:id>/', views.SpellSheet.as_view(), name="spell"),

    path('item/<int:id>/', views.main_view, name="item"),
    path('search/', views.main_view, name="search"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_main.urls')), # Home
    path('users/', include('app_users.urls')), # User managemant
    path('legends/', include('app_legends.urls')), # Legends system
    # path('d&d/'), # D&D system
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_legends/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def main_view(request):
    return HttpResponse('App legends')

app_legends/views/character_edit.py
from django.views import View
from django.shortcuts import render, redirect
from django.urls import reverse
from app_legends.models import Character, CharacterStats, Race, Specialization, Skill
from app_legends.forms import CharacterEditForm
from app_main.models import RPGSystem
from django.http import Http404
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

@method_decorator(
    login_required(login_url='users:login_view', redirect_field_name='next'),
    name='dispatch'
)
class CharacterEdit(View):

    def get_character(self, request, id):
        character = Character.objects.filter(
            id=id,
            editor=request.user,
        ).first()

        if not character:
            raise Http404()

        return character
    
    def get_old_skills(self, character):
        old_skills = [character.specialization.startingSkill]
        old_skills += character.race.skills.all()

        return old_skills
    
    def get_new_skills(self, request):
        race = Race.objects.filter(
            id=request.POST.get('race')
        ).first()
        specialization = Specialization.objects.filter(
            id=request.POST.get('specialization')
        ).first()
        new_skills = [specialization.startingSkill]
        new_skills += race.skills.all()
        
        return new_skills

    def get(self, request, id):
        character = self.get_character(request, id)
        systems = RPGSystem.objects.all().order_by('name')

        form = CharacterEditForm(
            request.POST or None,
            request.FILES or None,
            instance=character
        )

        context = {
            'systems': systems,
            'form': form,
            'form_title': f'Editor de ficha - {character.name}',
            'character': character,
        }

        return render(request, 'legends/pages/character-edit.html', context)
    
    def post(self, request, id):
        character = self.get_character(request, id)
        old_skills = self.get_old_skills(character)
        character_stats = CharacterStats.objects.filter(character=character).first()

        form = CharacterEditForm(
            request.POST or None,
            request.FILES or None,
            instance=character
        )

        if form.is_valid():
            character = form.save(commit=False)
            if not character.creator:
                character.creator = request.user
            if not character.editor:
                character.editor = request.user

            new_skills = self.get_new_skills(request)
            for old_skill in old_skills:
                character.skills.remove(old_skill)
            for new_skill in new_skills:
                character.skills.add(new_skill)
            character.save()
            character_stats.save()
            
            messages.success(request, 'Personagem editado com sucesso!')
            
        return redirect(reverse('legends:character_sheet', kwargs={'id': id}))
    

app_legends/views/character_edit_attribute.py
from django.views import View
from django.shortcuts import render, redirect
from django.urls import reverse
from app_legends.models import Character, CharacterExpertise, CharacterAttribute
from app_legends.forms import CharacterEditForm
from app_main.models import RPGSystem
from django.http import Http404, JsonResponse
from django.contrib import messages

class CharacterEditAttribute(View):
    
    def post(self, request, id):
        character = Character.objects.filter(id=id).first()
        attribute_id = request.POST.get('attribute_id')
        attribute = CharacterAttribute.objects.filter(id=attribute_id).first()
        if attribute:
            if request.POST.get('type') == 'raise':
                if attribute.level < 70 and character.remainingPoints > 0:
                    attribute.level += 1
                    attribute.save()
                    character.save()
            if request.POST.get('type') == 'decrease':
                if attribute.level > 0 and attribute.remaining > 0:
                    attribute.level -= 1
                    attribute.save()
                    character.save()
            
        return redirect(reverse('legends:character_sheet', kwargs={'id': id}))
    

app_legends/views/character_edit_expertise.py
from django.views import View
from django.shortcuts import redirect
from django.urls import reverse
from app_legends.models import Character, CharacterExpertise, CharacterAttribute, CharacterStats, CharacterWeapon, Weapon

class CharacterEditExpertise(View):
    def post(self, request, id):
        character = Character.objects.filter(id=id).first()
        characterStats = CharacterStats.objects.filter(character=character).first()
        characterWeapons = CharacterWeapon.objects.filter(character=character).order_by('-id')
        attribute_id = request.POST.get('attribute_id')
        attribute = CharacterAttribute.objects.filter(id=attribute_id).first()
        expertise_id = request.POST.get('expertise_id')
        expertise = CharacterExpertise.objects.filter(id=expertise_id).first()
        if expertise and attribute:
            if request.POST.get('type') == 'raise':
                if expertise.level < 10 and attribute.remaining > 0:
                    expertise.level += 1
            if request.POST.get('type') == 'decrease':
                if expertise.level > -1:
                    expertise.level -= 1
            expertise.save()
            attribute.save()
            character.save()
            characterStats.save()
            for weapon in characterWeapons:
                weapon.save()
            
        return redirect(reverse('legends:character_sheet', kwargs={'id': id}))
    

app_legends/views/character_edit_image.py
from django.views import View
from django.shortcuts import render, redirect
from django.db.models import Q
from app_legends.models import Character
from app_legends.forms import CharacterEditImageForm
from app_main.models import RPGSystem
from django.http import Http404
from django.urls import reverse
from django.contrib import messages

class CharacterEditImage(View):
    ...
    # def get_character(self, request, id):
    #     character = Character.objects.filter(
    #         Q(public=True) |
    #         Q(editor=request.user),
    #         id=id,
    #     ).first()
    #     if not character:
    #         raise Http404()
    #     return character

    # def get(self, request, id):
    #     systems = RPGSystem.objects.all().order_by('name')
    #     character = self.get_character(request, id)
    #     form = CharacterEditImageForm(request.POST or None, request.FILES or None)
    #     context = {
    #         'systems': systems,
    #         'header_title': 'Legends',
    #         'character': character,
    #         'form': form,
    #     }

    #     return render(request, 'legends/pages/character_edit_image.html', context)
    
    # def post(self, request, id):
    #     character = self.get_character(request, id)
    #     form = CharacterEditImageForm(request.POST or None, request.FILES or None)

    #     if form.is_valid():
    #         print('deu certo')
        
    #     url = reverse('legends:character_list')
    #     return redirect(url)

def character_edit_image(request, id):
    character = Character.objects.filter(
            Q(public=True) |
            Q(editor=request.user),
            id=id,
        ).first()
    form = CharacterEditImageForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        new_instance = form.save(commit=False)
        character.ilustration = new_instance.ilustration
        character.save()

    context = {
        'form': form,
        'return': reverse('legends:character_sheet', args={id,}),
    }
    return render(request, 'legends/pages/character-edit-image.html', context)

app_legends/views/character_edit_level.py
from django.views import View
from django.shortcuts import redirect
from django.urls import reverse
from app_legends.models import Character, CharacterExpertise, CharacterAttribute, CharacterStats

class CharacterEditLevel(View):
    
    def post(self, request, id):
        character = Character.objects.filter(id=id).first()
        character_stats = CharacterStats.objects.filter(character=character).first()
        character_expertises = CharacterExpertise.objects.filter(character=character)
        new_level = int(request.POST.get('level'))
        if new_level > 20:
            new_level = 20
        elif new_level < 1:
            new_level = 1
        character.level = new_level 
        character.save()
        character_stats.save()
        for expertise in character_expertises:
            expertise.save()
            
        return redirect(reverse('legends:character_sheet', kwargs={'id': id}))
    

app_legends/views/character_edit_skills.py
from django.views import View
from django.shortcuts import redirect
from django.urls import reverse
from app_legends.models import Character, CharacterStats, CharacterExpertise

class CharacterEditSkills(View):
    
    def post(self, request, id):
        character = Character.objects.filter(id=id).first()
        character_stats = CharacterStats.objects.filter(character=character).first()
        character_expertise = CharacterExpertise.objects.filter(character=character).first()
        character.skills.set(request.POST.getlist('skills'))
        character.save()
        character_stats.save()
        character_expertise.save()
            
        return redirect(reverse('legends:character_sheet', kwargs={'id': id}))
    

app_legends/views/character_edit_stats_bars.py
from django.views import View
from django.shortcuts import redirect
from django.urls import reverse
from app_legends.models import Character, CharacterStats

class CharacterEditStatsBars(View):
    
    def post(self, request, id):
        character = Character.objects.filter(id=id).first()
        character_stats = CharacterStats.objects.filter(character=character).first()
        if request.POST.get('type') == 'energy':
            character_stats.currentEP = int(request.POST.get('current_ep'))
            character_stats.save()
        if request.POST.get('type') == 'health':
            character_stats.currentHP = int(request.POST.get('current_hp'))
            character_stats.save()
            
        return redirect(reverse('legends:character_sheet', kwargs={'id': id}))
    

app_legends/views/character_sheet.py
from django.views import View
from django.shortcuts import render, redirect
from django.db.models import Q
from app_legends.forms import CharacterEditSkillsForm
from app_legends.models import Character, CharacterAttribute, CharacterExpertise, CharacterStats, CharacterWeapon, Weapon, DamageType
from app_main.models import RPGSystem
from django.http import Http404

class CharacterSheet(View):

    def get(self, request, id):
        systems = RPGSystem.objects.all().order_by('name')
        character = Character.objects.filter(
            Q(public=True) |
            Q(editor=request.user),
            id=id,
        ).first()
        if not character:
            raise Http404()
        character_attributes = CharacterAttribute.objects.filter(
            character=character
        ).order_by('id')
        character_expertises = CharacterExpertise.objects.filter(
            character=character
        ).order_by('id')
        character_stats = CharacterStats.objects.filter(
            character=character
        ).first()
        character_weapons = CharacterWeapon.objects.filter(
            character=character
        ).order_by('id')
        base_weapons = Weapon.objects.filter(
            rarity='Comum'
        ).order_by('combat', '-type')
        damage_types = DamageType.objects.all().order_by('name')
        skills_form = CharacterEditSkillsForm(
            request.POST or None,
            instance=character
        )
        
        context = {
            'systems': systems,
            'header_title': 'Legends',
            'base_weapons': base_weapons,
            'character': character,
            'char_attrs': character_attributes,
            'char_exper': character_expertises,
            'char_stats': character_stats,
            'char_weapons': character_weapons,
            'damage_types': damage_types,
            'skills_form': skills_form,
        }

        return render(request, 'legends/pages/character-sheet.html', context)
    
    def post(self, request, id):
        return redirect('legends:character_sheet', kwargs={'id': id})

app_legends/views/character_weapon_create.py
from django.views import View
from django.shortcuts import redirect
from django.urls import reverse
from app_legends.models import Character, CharacterWeapon, Weapon

class CharacterWeaponCreate(View):
    def post(self, request, id):
        character = Character.objects.filter(
            id=id
        ).first()
        base_weapon = Weapon.objects.filter(
            name='Porrete'
        ).first()
        new_character_weapon = CharacterWeapon.objects.create(
            character=character,
            weapon=base_weapon,
            name='Nova arma!',
            damageType=base_weapon.damageType,
            weight=base_weapon.weight,
        )

        character.save()
        new_character_weapon.save()
            
        return redirect(reverse('legends:character_sheet', kwargs={'id': id}))
    

app_legends/views/character_weapon_delete.py
from django.views import View
from django.shortcuts import redirect
from django.urls import reverse
from app_legends.models import CharacterWeapon

class CharacterWeaponDelete(View):
    def post(self, request, id):
        character_weapon = CharacterWeapon.objects.filter(
            id=id
        ).first()
        character_id = character_weapon.character.id
        character_weapon.delete()
            
        return redirect(reverse('legends:character_sheet', kwargs={'id': character_id}))
    

app_legends/templates/legends/partials/character-sheet-attribute-card.html
<div class="attribute-card-container">
    <div class="attribute-card-content">
        <div class="attribute-card-level">
            <form action="{% url "legends:character_edit_attribute" character.id %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="attribute_id" value="{{ attr.id }}">
                <input type="hidden" name="type" value="decrease">
                {% if attr.remaining > 0 %}
                    <button class="attribute-edit-button"><i class="fa-solid fa-minus"></i></button>
                {% endif %}  
            </form>
            <h2>{{ attr.level }}</h2>
            <form action="{% url "legends:character_edit_attribute" character.id %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="attribute_id" value="{{ attr.id }}">
                <input type="hidden" name="type" value="raise">
                {% if character.remainingPoints > 0 %}
                    <button class="attribute-edit-button"><i class="fa-solid fa-plus"></i></button>
                {% endif %}
            </form>
        </div>
        <div class="attribute-card-name">
            {{ attr.name }}
        </div>
    </div>
</div>

app_legends/templates/legends/partials/character-sheet-energy.html

<div class="energy-stats">
    MP<i class="fa-solid fa-bolt"></i>
    <form action="{% url 'legends:character_edit_stats' character.id %}" method="POST" class="energy-form">
        {% csrf_token %}
        <div class="energy-bar">
            <div class="energy-values">
                <div id="energy-current">
                    <input type="hidden" name="type" value="energy">
                    <input type="text" name="current_ep" id="energy-input" value="{{ char_stats.currentEP }}">
                </div> / 
                <div id="energy-max">
                    {{ char_stats.maxEP }}
                </div>
            </div>
            <div id="inner-energy-bar"></div>
        </div>
    </form>
</div>

app_legends/templates/legends/partials/character-sheet-expertises.html
<div class="character-sheet-expertises">   
    {% for attr in char_attrs %}
        <div class="character-sheet-expertises-column">
            <div class="character-sheet-expertises-title">
                <h3>{{ attr.name }}:</h3>
                <p>{{ attr.remaining }}</p>
            </div>
            {% for expertise in attr.expertises.all %}
                <div class="expertise">
                    <div class="expertise-info">
                        <p class="{% if expertise.proficient %}proficient{% endif %} expertise-name">{{ expertise.expertise }}:</p>
                        <p class="expertise-value">{{expertise.value}}</p>
                    </div>
                    <form action="{% url "legends:character_edit_expertise" character.id %}" method="POST">
                        {% if expertise.level > -1 %}
                            {% csrf_token %}
                            <input type="hidden" name="attribute_id" value="{{ attr.id }}">
                            <input type="hidden" name="expertise_id" value="{{ expertise.id }}">
                            <input type="hidden" name="type" value="decrease">
                            <button class="expertise-edit-button"><i class="fa-solid fa-minus"></i></button>
                        {% endif %}
                    </form>
                    <form action="{% url "legends:character_edit_expertise" character.id %}" method="POST">
                        {% if attr.remaining > 0 and expertise.level < 10 %}
                            {% csrf_token %}
                            <input type="hidden" name="attribute_id" value="{{ attr.id }}">
                            <input type="hidden" name="expertise_id" value="{{ expertise.id }}">
                            <input type="hidden" name="type" value="raise">
                            <button class="expertise-edit-button"><i class="fa-solid fa-plus"></i></button>
                        {% endif %}
                    </form>
                </div>
            {% endfor %}
        </div>
    {% endfor %}
</div>

app_legends/templates/legends/partials/character-sheet-habilities.html
<div class="character-sheet-habilities">
    <h2>HABILIDADES</h2>
    <div class="habilities-container">
        <div class="current-habilities-container">
            <h3>Habilidades Atuais</h3>
            <div class="current-habilities-grid">
                {% for skill in character.skills.all %}
                    <ul><li><a href="{% url "legends:skill" skill.id %}">{{ skill.name }}</a></li></ul>
                {% endfor %}
            </div>
        </div>
        <div class="edit-habilities-container">
            <h3>Editar</h3>
            <form action="{% url "legends:character_edit_skills" character.id %}" method="post">
                {% csrf_token %}
                <div class="edit-habilities-grid">
                    {% for field in skills_form %}
                        {{ field }}
                    {% endfor %}
                </div>
                <button type="submit">Atualizar</button>
            </form>   
        </div>
    </div> 
</div>

app_legends/templates/legends/partials/character-sheet-header.html
<div class="character-sheet-header">
    {% include "legends/partials/character-sheet-ilustration.html" %}
    <div class="character-sheet-points">
        <div class="character-sheet-attributes">
            {% for attr in char_attrs %}
                {% include "legends/partials/character-sheet-attribute-card.html" %}
            {% endfor %}
        </div>
        {% include "legends/partials/character-sheet-expertises.html" %}
    </div>
</div>

app_legends/templates/legends/partials/character-sheet-health.html
<div class="health-stats">
    HP<i class="fa-solid fa-heart"></i>
    <form action="{% url 'legends:character_edit_stats' character.id %}" method="POST" class="health-form">
        {% csrf_token %}
        <div class="health-bar">
            <div class="health-values">
                <div id="health-current">
                    <input type="hidden" name="type" value="health">
                    <input type="text" name="current_hp" id="health-input" value="{{ char_stats.currentHP }}">
                </div> / 
                <div id="health-max">
                    {{ char_stats.maxHP }}
                </div>
            </div>
            <div id="inner-health-bar"></div>
        </div>
    </form>
</div>

app_legends/templates/legends/partials/character-sheet-ilustration.html
<div class="character-sheet-ilustration">
    {% if character.ilustration.url and character.editor == request.user %}
        <div class="character-sheet-ilustration-content">
            <a href="{% url "legends:character_edit_image" character.id %}">
                <img src="{{ character.ilustration.url }}" alt="">
            </a>
        </div>
    {% elif character.editor == request.user %}
        <div class="character-sheet-ilustration-content no-image">
            <a href="{% url "legends:character_edit_image" character.id %}">
                <p>Nenhuma imagem encontrada!</p>
                <p>Clique aqui para adicionar uma ilustração para {{ character.name }}.</p>
            </a>
        </div>
    {% else %}
        <div class="character-sheet-ilustration-content">
            <img src="{{ character.ilustration.url }}" alt="">
        </div>
    {% endif %}
</div>

app_legends/templates/legends/partials/character-sheet-stats.html
<div class="stats">
    <div class="main-stats">
        {% include "legends/partials/character-sheet-health.html" %}
        <div class="stats-group">
            <div class="armor-stats">
                CA<i class="fa-solid fa-shield"></i><div class="armor-points">{{ char_stats.armorClass }}</div>
            </div>
            <div class="perception-stats">
                PP<i class="fa-solid fa-eye"></i><div class="perception-points">{{ char_stats.passivePerception }}</div>
            </div>
        </div>
        <div class="stats-group">
            <div class="attribute-stats">
                PA<i class="fa-solid fa-file-lines"></i><div class="attribute-points">{{ character.remainingPoints }}</div>
            </div>
            <div class="level-stats">
                Nível<i class="fa-solid fa-dice-d20"></i>
                <div class="level-points">
                    <form action="{% url "legends:character_edit_level" character.id %}" method="POST" class="level-form">
                        {% csrf_token %}
                        <input type="text" name="level" value="{{ character.level }}">
                    </form>
                </div>
            </div>
        </div>
        {% include "legends/partials/character-sheet-energy.html" %}
        <div class="stats-group">
            <div class="movement-stats">
                BP<i class="fa-solid fa-angles-up"></i><div class="movement-points">+ {{ character.proficiency }}</div> 
            </div>
            <div class="movement-stats">
                VM<i class="fa-solid fa-person-walking"></i><div class="movement-points">{{ char_stats.movement }} M.</div> 
            </div>
        </div>
        <div class="stats-group">
            <div class="race-stats">
                Raça<i class="fa-solid fa-person"></i><div class="race-points"><a href="{% url "legends:race" character.race.id %}">{{ character.race }}</a></div> 
            </div>
            <div class="specialization-stats">
                Classe<i class="fa-solid fa-screwdriver-wrench"></i><div class="specialization-points"><a href="{% url "legends:specialization" character.specialization.id %}">{{ character.specialization }}</a></div> 
            </div>
        </div>
    </div>
</div>

app_legends/templates/legends/partials/character-sheet-weapon-card.html
<div class="weapon-card">
    <div class="weapon-card-name">
        <form action="{% url "legends:character_weapon_update_name" weapon.id %}" method="POST">
            {% csrf_token %}
            <input type="text" name="weapon_name" value="{{ weapon.name }}"> 
        </form>
    </div>
    <div class="weapon-card-weapon-type">
        <form action="{% url "legends:character_weapon_update_weapon_type" weapon.id %}" method="POST">
            {% csrf_token %}
            <select name="weapon_type" value="{{ weapon.weapon.name }}">
                {% for base in base_weapons %}
                    <option {% if weapon.weapon.name == base.name %} selected="selected" class="weapon-card-selected" {% endif %} value="{{ base.name }}">{{ base.name }}</option>
                {% endfor %}
            </select>
            <button type="submit"><i class="fa-solid fa-check"></i></button>
        </form>
    </div>
    <div class="weapon-card-modifier">
        <form action="{% url "legends:character_weapon_update_modifier" weapon.id %}" method="POST">
            {% csrf_token %}
            <select name="weapon_modifier">
                {% if weapon.modifier %}
                    <option value="Nenhum">Nenhum</option>   
                    <option selected="select" value="{{ weapon.modifier.name }}">{{ weapon.modifier.name }}</option>
                {% else %}
                    <option selected="selected" value="Nenhum">Nenhum</option>   
                {% endif %}
                
                {% for modifier in weapon.weapon.modifiers.all %}
                    {% if weapon.modifier != modifier %}
                        <option value="{{ modifier.name }}">{{ modifier.name }}</option>
                    {% endif %}
                {% endfor %}
            </select>
            <button type="submit"><i class="fa-solid fa-check"></i></button>
        </form>
    </div>
    <div class="weapon-card-combat-range">
        {{ weapon.weapon.combatRange }} metros
    </div>
    <div class="weapon-card-shot-range">
        {% if weapon.weapon.shotRange %}
            {{ weapon.weapon.shotRange }} metros
        {% else %}
            - - - metros                                  
        {% endif %}
    </div>
    <div class="weapon-card-attack">
        {{ weapon.attackRoll }}
    </div>
    <div class="weapon-card-damage">
        {{ weapon.finalDamage }}
    </div>
    <div class="weapon-card-damage-type">
        <form action="{% url "legends:character_weapon_update_damage_type" weapon.id %}" method="POST">
            {% csrf_token %}
            <select name="weapon_damage_type" value="{{ weapon.damageType.name }}">
                {% for damage_type in damage_types %}
                    <option {% if weapon.damageType.name == damage_type.name %} selected="selected" {% endif %} value="{{ damage_type.name }}">{{ damage_type.name }}</option>
                {% endfor %}
            </select>
            <button type="submit"><i class="fa-solid fa-check"></i></button>
        </form>
    </div>
    <div class="weapon-card-weight">
        <input type="text" name="weapon_weight" value="{{ weapon.weapon.weight }}"> Kg
    </div>
    <div class="weapon-card-delete">
        <form action="{% url "legends:character_weapon_delete" weapon.id %}" method="POST">
            {% csrf_token %}
            <button type="submit"><i class="fa-solid fa-trash"></i></button>
        </form>
    </div>
</div>  